### ISSUE TITLE
Single line comment after macro causes meta.preprocessor.conditional.cpp scope to leak

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-cpp-syntax#494]
Originally from @MrSparc in https://github.com/microsoft/vscode/issues/102687

Checklist

- [ ] This problem exists even with the setting `"C_Cpp.enhancedColorization": "Disabled"`
- [ ] This bug exists for C
- [x] This bug exists for C++
- [ ] This bug exists for Objective-C
- [ ] This bug exists for Objective-C++

## The code with a problem is:
```c++
void foo(const char *uri)
{
  if (uri == NULL) {
    printf("uri is nullptr\n");
  } else if (strncmp(uri, "/put?", 5) == 0) {
    printf("PUT\n");
#ifdef ALLOW_POST // a comment here prevents the code after the '?' char from being correctly parsed by the grammar syntax rules for C++
  } else if (strncmp(uri, "/post?", 6) == 0) {
    printf("POST\n");
#endif
  } else if (strncmp(uri, "/get?", 5) == 0) {
    printf("GET\n");
  } else {
    printf("unknown\n");
  }
}
```

## It looks like:
![cpp_syntax_higthlight_issue](https://user-images.githubusercontent.com/2487742/87656310-3b562080-c751-11ea-9ebb-22c4df3bb66d.gif)

## It should look like:
The comment shouldn't cause the scopes on the following lines to get `meta.preprocessor.conditional.cpp`. A `/**/` comment works fine, but a `//` comment causes this problem

**Comment by jeff-hykin** [comment]
fixed
